### PR TITLE
Fix integration test failures by making Node::with_conf more robust

### LINKED ISSUE #205: Random integration test failures because: `it appears that bitcoind is not reachable`
There are random integration test failures both in CI and locally, it fails once every 5 or 10 runs. Issue #147 may be related but the suggestion there does not seem to fix this.
The error message is always:
```
failed to create node: it appears that bitcoind is not reachable
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Running the tests in only a single thread always passes in my testing, so I thought it might be due to the race condition fixed in https://github.com/bitcoin/bitcoin/pull/30394, but it still happens in v27.2 and v28.1. Using only a single thread takes about 4 times as long so is not really a solution.

### PR DESCRIPTION
**Pull request by jamillambert**
The intermittent integration test failures are caused by race conditions in the creation of the node, wallet or the cookie file. Change `Node::with_conf` to check if there is a problem and retry the section where it occurred, or if that still fails retry the whole process of starting the node.

First patch: 
- Split out some sections into helper functions.

Second patch:
- Remove the loop in `with_conf()` that creates `client`, instead loop over the individual parts.
- Create helper functions for creating the `client`, and creating or loading the client `wallet`, both with their own retry logic.
- Reduce the sleep time between retries to reduce the delay, since it looks like the errors happen over shorter time periods than the existing 1 second wait.
- Add functions to wait until the client and the cookie file are available.
- Add a loop to retry the whole process if it fails, since the integration tests pass when repeated, just repeat this section where the failures occur instead.
- Remove all the debugging outputs since it all works now they are not needed.
- Update the rustdocs for the function.

Third patch: 
- Revert #206, since the issue is now solved at it’s source the pause is no longer needed.

Closes #205

### CODE REVIEW

File: node/src/lib.rs [hunk 1]
```diff
@@ -280,8 +280,104 @@ impl Node {
         Node::with_conf(exe, &Conf::default())
     }
 
-    /// Launch the bitcoind process from the given `exe` executable with given [Conf] param and create/load the "default" wallet.
+    /// Launch the bitcoind process from the given `exe` executable with given [Conf] param and
+    /// create/load the "default" wallet.
```
Comment (tcharding) [inline node/src/lib.rs:284]:
```suggestion
    /// create/load the "default" wallet.
    ///
```

File: node/src/lib.rs [hunk 2]
```diff
@@ -280,8 +280,104 @@ impl Node {
...
+                    let _ = process.kill();
+                    continue;
+                }
+                Ok(None) => {
+                    // Process is still running, proceed
+                }
+            }
+
+            if Self::wait_for_cookie_file(cookie_file.as_path(), Duration::from_secs(5)).is_err() {
+                let _ = process.kill();
```
Comment (tcharding) [inline node/src/lib.rs:339]: Maybe a code comment here saying why we kill the process if waiting for the cookie file fails?

File: node/src/lib.rs [hunk 3]
```diff
@@ -280,8 +280,104 @@ impl Node {
...
+            let client_base = Self::create_client_base(&rpc_url, &auth)?;
+            let client = match &conf.wallet {
+                Some(wallet) =>
+                    match Self::create_client_wallet(&client_base, &rpc_url, &auth, wallet) {
+                        Ok(client) => client,
+                        Err(e) =>
+                            if attempt == conf.attempts - 1 {
+                                return Err(e);
+                            } else {
+                                let _ = process.kill();
```
Comment (tcharding) [inline node/src/lib.rs:353]: And here maybe a comment saying why we kill after waiting for client fails.

File: node/src/lib.rs [hunk 4]
```diff
@@ -280,8 +280,104 @@ impl Node {
...
+                                continue;
+                            },
+                    },
+                None => client_base,
+            };
+            if Self::wait_for_client(&client, Duration::from_secs(5)).is_err() {
+                let _ = process.kill();
```
Comment (tcharding) [inline node/src/lib.rs:360]: And here.

File: node/src/lib.rs [hunk 5]
```diff
@@ -293,170 +389,119 @@ impl Node {
...
+            match Client::new_with_auth(rpc_url, auth.clone()) {
+                Ok(client) => return Ok(client),
+                Err(e) =>
+                    if tries == 10 {
+                        return Err(Error::NoBitcoindInstance(e.to_string()).into());
+                    },
+            }
+            thread::sleep(Duration::from_millis(200));
+        }
+        unreachable!()
```
Comment (tcharding) [inline node/src/lib.rs:474]: Perhaps this is cleaner?

```rust
        for _ in 0..9 {
            if let Ok(client) = Client::new_with_auth(rpc_url, auth.clone()) {
                return Ok(client);
            }
            thread::sleep(Duration::from_millis(200));
        }
        Client::new_with_auth(rpc_url, auth.clone()).map_err(|e| Error::NoBitcoindInstance(e.to_string()).into())
```

**Review by tcharding — COMMENTED** [review]
Mad, good work man.

File: node/src/lib.rs (hunk 2 above)
Comment (jamillambert) [reply node/src/lib.rs:339]: I have added comments to all the checks where it kills the process and retries.
