### PR TITLE
Improve ListUnspent data handling: Fix deserialization & add into_model

### LINKED ISSUE #187: ListUnspentItem expects account to be present
When calling the `listunspent` function on a wallet, it is possible to run into 

```
JsonRpc(Json(Error("missing field `account`", line: 1, column: 391)))
```

This is because `account` is not present on the response at all - while it has been deprecated and is documented as such, `ListUnspentItem` still expects it to be present.

<details><summary>bitcoin-cli  v28.1.0</summary>
<pre>
$ sudo bitcoin-cli -datadir=/home/bitcoin/bitcoind -rpcwallet=watch_2 listunspent
[
  {
    "txid": "c6003f8713678ea143be0d9b8fdcf38c060443e288d8b9591d653195fe5e6475",
    "vout": 2,
    "address": "bc1qmv2pxw5ahvwsu94kq5f520jgkmljs3af8ly6tr",
    "label": "imported_address",
    "scriptPubKey": "0014db14133a9dbb1d0e16b60513453e48b6ff2847a9",
    "amount": 0.00062500,
    "confirmations": 12,
    "spendable": true,
    "solvable": false,
    "parent_descs": [
      "addr(bc1qmv2pxw5ahvwsu94kq5f520jgkmljs3af8ly6tr)#688lxve7"
    ],
    "safe": true
  },
  {
    "txid": "e6be366f4c2a1d39c0dce2996a2034c53c5fd36d032bed2f1c900fa39e64ed1c",
    "vout": 1,
    "address": "bc1qmv2pxw5ahvwsu94kq5f520jgkmljs3af8ly6tr",
    "label": "imported_address",
    "scriptPubKey": "0014db14133a9dbb1d0e16b60513453e48b6ff2847a9",
    "amount": 0.00062500,
    "confirmations": 12,
    "spendable": true,
    "solvable": false,
    "parent_descs": [
      "addr(bc1qmv2pxw5ahvwsu94kq5f520jgkmljs3af8ly6tr)#688lxve7"
    ],
    "safe": true
  },
  {
    "txid": "1489216b60349070e30f0f9fa62853071c6e15c5a428eaf1e9d87438d6bd7a31",
    "vout": 2,
    "address": "bc1qmv2pxw5ahvwsu94kq5f520jgkmljs3af8ly6tr",
    "label": "imported_address",
    "scriptPubKey": "0014db14133a9dbb1d0e16b60513453e48b6ff2847a9",
    "amount": 0.00075000,
    "confirmations": 5,
    "spendable": true,
    "solvable": false,
    "parent_descs": [
      "addr(bc1qmv2pxw5ahvwsu94kq5f520jgkmljs3af8ly6tr)#688lxve7"
    ],
    "safe": true
  }
]
</pre>
</details>

### LINKED ISSUE #189: into_model() method not implemented for ListUnspent
While writing a test for `listunspent` in relation to #187, I noticed that the `into_model` method is implemented only for `ListUnspentItem` and `ListUnspentItemError`, but not for the `ListUnspent` type itself.

I'm unsure if this was intentional, or if it would be appropriate to instead extract the `ListUnspentItem` from `ListUnspent` and use it to implement `into_model` for the overall `ListUnspent`. I also observed a similar pattern with errors—there is a `ListUnspentItemError`, but no `ListUnspentError`.

### PR DESCRIPTION
**Pull request by GideonBature**
While working on [#187](https://github.com/rust-bitcoin/corepc/issues/187), I wrote a test for the listunspent method to better understand the issue. The test timed out in my local environment, so I pushed it here to run in CI and confirm the behavior. I found that although the account field has been deprecated and is no longer included in the response, ListUnspentItem still expects it to be present, which causes a deserialization error.

While writing this test, I also discovered a related issue:
The into_model method is implemented for ListUnspentItem and ListUnspentItemError, but not for the top-level ListUnspent type. This makes it harder to convert the full response into a usable model and limits how we can work with the data.

Closes #187
Closes #189

### CODE REVIEW

**Comment by GideonBature** [comment]
I have confirmed that it throws the error as reported, I will start working on the fix now.

**Comment by GideonBature** [comment]
I just made the account field optional and made it to always return None for the account field when it is not returned.

**Comment by tcharding** [comment]
This is correct-ish but not in the spirit of the repo. The more correct solution is to create a now `types::v18::ListUnspent` type that does not have the `account` field. Also we should test the `into_model` logic if we are removing `UNTESTED`.

**Comment by GideonBature** [comment]
Noted... Will do that.

File: integration_test/tests/wallet.rs [hunk 1]
```diff
@@ -237,6 +237,22 @@ fn wallet__get_transaction__modelled() {
...
+    #[cfg(feature = "v17")]
+    let node = Node::with_wallet(Wallet::Default, &["-deprecatedrpc=accounts"]);
+
+    #[cfg(not(feature = "v17"))]
+    let node = Node::with_wallet(Wallet::Default, &[]);
+
+    node.fund_wallet();
+
+    let _json: ListUnspent = node.client.list_unspent()
+        .expect("listunspent RPC call failed");
```
Comment (tcharding) [inline integration_test/tests/wallet.rs:252]: Can you copy the style in the rest of the tests man please.

**Comment by tcharding** [comment]
What is the status of this man? Can you make the PR fix #189 and #187 and also implement `into_model` for `ListUnspent` and test it. Should all be reasonably easy to do and easy to review all together. Thanks.

**Comment by tcharding** [comment]
Note self, this PR will be a good test run for the recently merged labeller PR.

**Comment by GideonBature** [comment]
Definitely, I'll take care of these.

Also, I wanted to confirm whether `ListUnspentItemError` should be wrapped in a `ListUnspentError`, or if it's okay to use `ListUnspentItemError` directly?

**Comment by tcharding** [comment]
I'd just return it directly i.e. return the first error. That is what I've been doing in a bunch of other places. Good question.

**Comment by tcharding** [comment]
You can ignore the PR Labeler job fail. I don't have time to debug it at the moment. @0xZaddyy do you have time to look into it please?

**Comment by 0xZaddyy** [comment]
Yesss sure, I'm already on it

**Comment by GideonBature** [comment]
> I'd just return it directly i.e. return the first error. That is what I've been doing in a bunch of other places. Good question.

Alright. Thank you... It makes sense that way, as if the first item fails, it's very likely the others will have same failure as well.

**Comment by 0xZaddyy** [comment]
> Legend.

Figured why the job fails, I'll make amends as soon as possible.

**Comment by tcharding** [comment]
Can you rebase on master please.

File: integration_test/tests/wallet.rs [hunk 2]
```diff
@@ -237,6 +237,30 @@ fn wallet__get_transaction__modelled() {
...
+    #[cfg(not(feature = "v17"))]
+    {
+        let node = Node::with_wallet(Wallet::Default, &[]);
+        node.fund_wallet();
+
+        let json: ListUnspent = node.client.list_unspent().expect("listunspent");
+        let model: Result<mtype::ListUnspent, ListUnspentItemError> = json.into_model();
+        model.unwrap();
+    }
+}
```
Comment (tcharding) [inline integration_test/tests/wallet.rs:261]: why note use that new match pattern stlye to cfg the node constructor? (Like we did just recently.) Will make this way more terse.

File: types/src/v18/wallet/error.rs [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+
+use bitcoin::amount::ParseAmountError;
+use bitcoin::{address, hex};
+
+use crate::error::write_err;
+use crate::NumericError;
+
+/// Error when converting a `ListUnspentItem` type into the model type.
+#[derive(Debug)]
+pub enum ListUnspentItemError {
```
Comment (tcharding) [inline types/src/v18/wallet/error.rs:13]: We can just re-use the v17 error because its the same (account is not converted so does not contribute to the error).

File: types/src/v17/wallet/into.rs [hunk 4]
```diff
@@ -655,6 +655,17 @@ impl ListUnspentItem {
     }
 }
 
+impl ListUnspent {
```
Comment (tcharding) [inline types/src/v17/wallet/into.rs:658]: I'm super anal about code layout in the file. I try to always put things _before_ where they are used, so this should be above the `ListUnspentItem` struct.

File: types/src/v17/wallet/into.rs [hunk 5]
```diff
@@ -655,6 +655,17 @@ impl ListUnspentItem {
...
+    /// Converts version specific type to a version nonspecific, more strongly typed type.
+    pub fn into_model(self) -> Result<model::ListUnspent, ListUnspentItemError> {
+        self.0
+            .into_iter()
+            .map(|item| item.into_model())
+            .collect::<Result<Vec<_>, _>>()
+            .map(model::ListUnspent)
+    }
+}
```
Comment (tcharding) [inline types/src/v17/wallet/into.rs:667]: Nice!

File: types/src/v18/wallet/into.rs [hunk 6]
```diff
@@ -0,0 +1,51 @@
...
+            confirmations,
+            redeem_script,
+            spendable: self.spendable,
+            solvable: self.solvable,
+            safe: self.safe,
+        })
+    }
+}
+
+impl ListUnspent {
```
Comment (tcharding) [inline types/src/v18/wallet/into.rs:42]: Above the `ListUnspentItem` please.

**Review by tcharding — COMMENTED** [review]
Looking good man! A few minor things please, then this is good to go. Nice bug fix.

**Comment by tcharding** [comment]
And rebase on master while you are at it please in case the labeller job is fixed.

File: integration_test/tests/wallet.rs (hunk 2 above)
Comment (GideonBature) [reply integration_test/tests/wallet.rs:261]: yes....

File: types/src/v17/wallet/into.rs (hunk 5 above)
Comment (GideonBature) [reply types/src/v17/wallet/into.rs:667]: Thank you!

**Comment by GideonBature** [comment]
I don't know why it's still showing that I don't have the permission to create labels, even after rebase and pushing...

**Comment by GideonBature** [comment]
> > I don't know why it's still showing that I don't have the permission to create labels, even after rebase and pushing...
> 
> I fixed it manually for this PR, there was still an issue with the workflow file which is fixed in #201

Oh, I see. Seems the master branch is yet to have this fix... Thank you for your help :).

**Review by tcharding — APPROVED** [review]
ACK f1573c289fd719ab8e96e99e5717b7fe416986ea
